### ISSUE TITLE
Cannot seem to get it to work

### ISSUE THREAD

**Issue by silverwind** [albinotonnina/parcel-plugin-inlinesvg#2]
I've studied both your examples but cannot figure out why your examples receive a SVG string from the import, while I always get URLs. I have the plugin in my dependencies and import the SVG file with a relative path.

Would you be so kind an take a minute to look at this minimal example:

```console
git clone https://github.com/silverwind/inlinesvgtest
cd inlinesvgtest
npm i
npm start
```

This example should output a undesired ` /dist/03b8341b6ec324aad741016911ea1ec9.svg`.

**Comment by jeremiedubuis** [comment]
I have had the same problem when not using --no-cache mode.

**Comment by fritx** [comment]
I had a fork of this repo:

```js
class InlineSvgAsset extends JSAsset {
  async load() {
    const file = read(this.name, "binary");
    return `module.exports = ${JSON.stringify(file)};`
  }

  pretransform() {}
  transform() {}
}
```

'cause I don't need svgo, and seems it broke my inlined svg defs!
For example, my `.svg` was `<svg><defs></defs><symbol></symbol></svg>`,
and the resolved text was cut without any `<symbol>` tags.

**Comment by albinotonnina** [comment]
@fritx will add the option to bypass svgo, I would add options to the plugin, also to configure svgo? Although that could make the plugin almost useless.
To inline an asset (eg. an svg), in Parcel you could do what is described here:
https://parceljs.org/assets.html

```
import fs from 'fs';

// Read contents as a string
const string = fs.readFileSync(__dirname + '/test.txt', 'utf8');

// Read contents as a Buffer
const buffer = fs.readFileSync(__dirname + '/test.png');
```

**Comment by albinotonnina** [comment]
@jeremiedubuis Yes I see the bug. I tried to investigate, no good news so far. Weird

**Comment by albinotonnina** [comment]
Closing, fixed by #5

**Comment by nihiluis** [comment]
will you publish a new package soon?

**Comment by albinotonnina** [comment]
@nihiluis try now
